### ISSUE TITLE
when calling findBinary() or exists() on a device where SuperSu is disabled - the thread is halted

### ISSUE THREAD

**Issue by KubebatHaMachatz** [Stericson/RootShell#21]
Hi all,

I'm using RootShell 1.3 and 1.4 in my apps. I stumbled upon a Samsung Galaxy S5 with Android 5.0 with SuperSu installed. When going into the Settings->Application Manager->SuperSu - there is no way to Uninstall it, The only option is to click on "Turn Off" which disables it from running.

When running my app ,which uses RootShell.isRootAvailable() and RootShell.isBusyboxAvailable(), I can see the application gets stuck and after about two minutes - there is an "Application not responding" dump in the Android monitor window in Android studio. Turning SuperSu beck on in app settings resolves this situation.

Debugging the code , It looks like the RootShell.isRootAvailable() and RootShell.isBusyboxAvailable() function run on the UI thread and the app is halted due to the inability to use SuperSu to us the commands findBinary.

On devices with SuperSu turned off - it would make sense to handle this situation with an exception or a return code that the will indicate a problem.

Any ideas as to how to resolve this issue? 

Thanks!

**Comment by KubebatHaMachatz** [comment]
Some additions to clarify things - isRootAvailable() and isBusyboxAvailable() are static functions and when called from the application object - they will run on the main thread.

**Comment by KubebatHaMachatz** [comment]
It turns out that the service I was using to run the isRootAvailable() and isBusyboxAvailable() functions executed on the main thread. once I changed the service base class from Service to IntentService (on which the onHandleIntent function is executed in a worker thread) - theproblem was resolved.

Still - it would be good if we could set a timeout on the functions that check the root status on a device. 

Thanks,

**Comment by KubebatHaMachatz** [comment]
Well , running the RooShell functions in a background thread didn't quite solve the issue. In one device - I see an Exception and the root check fails (so a rooted device is not recognized as rooted).

I tried this with RootShell versions 1.3 and 1.6.

This is the Exception stack trace:
01-29 14:58:36.413 23483-23812/? W/MessageQueue: Handler (com.stericson.RootShell.execution.Command$CommandHandler)
{1696c084} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (com.stericson.RootShell.execution.Command$CommandHandler) {1696c084}
sending message to a Handler on a dead thread
at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
at android.os.Handler.enqueueMessage(Handler.java:631)
at android.os.Handler.sendMessageAtTime(Handler.java:600)
at android.os.Handler.sendMessageDelayed(Handler.java:570)
at android.os.Handler.sendMessage(Handler.java:507)
at com.stericson.RootShell.execution.Command.terminated(Command.java:235)
at com.stericson.RootShell.execution.Command.terminate(Command.java:221)
at com.stericson.RootShell.execution.Command$ExecutionMonitor.run(Command.java:290)
